#+begin_export markdown
export const metadata = {
title: "Quotes & Poems"
}
#+end_export

* Quotes & Poems

Sometimes in life, it helps to have a few poems and quotes memorized.
Something about them cuts past the fluff of language in a way that makes the truth easier to find. 

Once you have them memorized, you'll be suprised by just how often you use them as little mental hooks to guide you in the right direction.

Here are the quotes and poems that I have found most useful.

-----

#+begin_quote
How we spend our days is, of course, how we spend our lives.

Annie Dillard
#+end_quote
-----

#+begin_quote
This is why we're here.
#+end_quote

-----

#+begin_quote
No citizen has a right to be an
amateur in the matter of physical
training... what a disgrace it is for a
man to grow old without ever
seeing the beauty and strength of
which his body is capable.

Socrates
#+end_quote

-----

#+begin_quote
War is and ugly thing, but not the ugliest of things.
The decayed and degraded state of moral and patriotic feeling
which thinks that nothing is worth war, is much worse...
The man who has nothing for which is willing to fight, nothing which is
more important than his own personal safety, is a miserable
creature and has no chance of being free unless made and kept
so by the exertions of better men than himself...

John Stewart Mill
#+end_quote

-----

> Invictus
> 
> Out of the night that covers me,  
> Black as the pit from pole to pole,  
> I thank whatever gods may be  
> For my unconquerable soul.  
>
> In the fell clutch of circumstance  
> I have not winced nor cried aloud.   
> Under the bludgeonings of chance  
> My head is bloody, but unbowed.  
>
> Beyond this place of wrath and tears  
> Looms but the Horor of the shade,  
> And yet the menace of the years  
> Finds and shall find me unafraid.  
>
> It matters not how strait the gate,  
> How charged with punishments the scroll,  
> I am the master of my fate,  
> I am the captian of my soul.  
>
> William Earnest Henely

-----

> This too shall pass.

------

> Discipline = Freedom
>
> Jocko Wilink

-----

> This beast is very mean: in fact  
> It will fight back, when it's attacked.  
>
> Vladimir Nabokov
