* Unified Mindfulness

This is a summary of:
- 'The Science of Enlightenment' by Shinzen Young
- the CORE Unified Mindfulness Training by Shinzen Young

I read the book first, then took the intro course.

The book was hugely important for me to validate mastery in
mindfulness as a worthy and attainable goal.

The course was hugely important for me to think about meditation
practice in more useful ways.

** The importance of meditation

Concentration is the most important skill you can acquire. Everything
in your life improves with your ability to focus on a single thing so
intensely that you lose yourself in it.

Shinzen makes the claim that with greatly heightened states of
concentration you essentially can slow down time and make your life
longer. Not longer in the number of years your body is alive, but
longer by vastly expanding the number of seconds in which you are
present.

Moments when you're present are really the only ones that count. They
are the moments that make life worth living at all.

Meditation is the path the super-concentration. That concentration can
be used to advance your career, enjoy relationships more, or
accomplish your goals.

Meditation will also make you happier by literally changing your
ability to control your suffering. Shinzen claims that unconditional
happiness, independent of circumstances, is well within the grasp of
mediators.

** Introduction to Mysticism

The book draws parallel between many different cultures and
religions. Shinzen makes the argument that all the most important
teaching from throughout history are in some ways pointing towards
contemplative practices.

Shinzen's deep knowledge of eastern languages connects lots of ideas
in ways I never would have been able to.

After reading the book, my appreciation for different religions has
grown. We are all searching for the same things, just in different ways.

Meditation is a method to harness the core of many religious experiences and truly understand spirituality by understanding yourself.

** Why Meditate

Meditation in Unified Mindfulness increases three things:

- Concentration power

  The ability to chose what to focus on. This is a fundamental control
  over your mind.

  Once you can choose your focus point, you can intentionally engross yourself in what makes you fulfilled.

- Sensory clarity

  Specific knowledge of individual sensations. Being able to
  distinguish and categorize all the different kinds of sensations.

  This clarity helps break down the illusion of self as a thing. As
  you untangle the mess of sensory experience that you perceive, the
  sense that you are separate from them dissipates.

- Equanimity

  A radical acceptance of all sensations. Acknowledging sensations
  without attaching to them. No pushing sensations away when we don't
  like them or pulling them close when we want to keep them.

  Buddhism teaches that suffering is conquerable by first conquering your grasping for control over outcomes.

  This is about recognizing the impermanence of all experiences.

** Categorizing Sensations

There are 3 attributes to each sensory experience.

1. Source

   Every sensation is either a *see*, *hear*, or *feel*.

2. Direction

   Every sensation is pointed *in* or *out*.

   'In' sensations deal with stuff in your mind like mental chatter,
   day dreaming, or emotions.

   'Out' sensations deal are outside of your mind. In the world around
   you or in your body.

3. Intensity

   Every sensation is active or restful.

   'Active' sensations are what we typically think of as
   sensations. For example, hearing a sound or feeling an itch.

   'Restful' sensations are the absence or relaxation of a
   sensation. For example, lack of mental chatter is an example of
   'Restful hear in'.

Sensory experiences can be labeled by specifying all three
attributes.

Typically, the 'out' direction and 'active' intensity are omitted when labeling.

Examples:
- "See in": A mental image of an apple
- "See rest": Relaxing your eyes or broaden your visual focus
- "Hear": The sound of a bird
- "Hear in rest": Lack of mental chatter
- "Feel in rest":

This categorization is powerful because any of the infinite possible
thoughts can be analyzed as a combination of a few simple
attributes.

The practice of labeling helps to untangle the mess of sensations we
experience which in turn helps us detach from them and lose our sense
of self being a separate object.

If that doesn't make sense, that's OK. The idea of losing the sense of
self is really hard to explain. Just trust that I'm not crazy.

** Gone

There is one more big concept that Unified Mindfulness introduces
about the nature of thought. The concept is called 'gone.' Gone is the
moment in which a sensory experience disappears or wanes.

When a car drives by and it start to get quieter, that's 'gone'.

When a light turns off and you can't see what's in front of you
anymore, that's 'gone'.

Gone exists in every moment because every moment is constant giving
way to a new moment.

Gone must be experienced in the moment in which something disappears,
not retrospectively.

** Meditation Practice

Practice can be done by focusing on any attribute or combination of
attributes within sensory experiences.

The first kind of practice that UM outlines is called 'Noting'.

Noting has 2 steps:
- Step 1: Recognize a sensory event

  This takes less than a second

- Step 2a: Focus intently on the sensation for a few seconds

  Saturate yourself in the experience

- Step 2b: If the sensation disappears, notice gone

- Repeat rhythmically for as long as your mediation sit lasts


The second practice is called labeling which builds upon noting. In
labeling, go through the rhythm of noting, but you also think or say a
label phrase that describes what you're noting.

Saying the label with an emotionally neutral voice helps practice
equanimity.

Most of energy should still be on experiencing the thing. 5% should be
on labeling.
