:PROPERTIES:
:TITLE: My journey learning Emacs
:END:

* Introduction

I like trying to make cool things appear on computer screens. 
If I want to be good at that, I need use and understand powerful tools that let me create efficiently.
This essay documents my journey learning what might be the most powerful software tool I've ever used - Emacs.

* Why I am choosing Emacs
  
I am fully devoted to using plaintext files for as many things in my life as possible.
I like that plaintext files are portable and eternal.
I like that they are easy to manipulate.
There are decades of tools available for manipulating plaintext files and if I can't find one that suits my needs, I can make one easily.
This allows me to do whatever I want with my data instead of being tied to the constraints of individual programs.

I like the idea of Emacs because it provides a platform that is fully customizable and extensible.
I plan on working with digital information and programs for my whole life, so I need an environment that I can customize and grow with me for the rest of my life.
Emacs has been around longer than any major text editor today, and according to the Lindy effect, that is a really good things.
Emacs is a difficult beast to learn, but if the effort is completed, the rewards of understanding such a powerful system will benefit me for as long as I am interested in making cool things appear on computer screens.

If you are completely unfamiliar with Emacs, this essay might not make any sense - read this primer first.

* Things I will use Emacs for
  
1. Web development
2. Writing (Org Mode)
3. Calendar and Task Mangement (Org Mode)
4. Personal finance (Ledger Mode)
5. Spaced repition software (Org-drill)
6. Reading
7. Email and news (Gnus)

* My perfect Emacs

I'm writing this section before diving into learning Emacs as a way to focus my learning to accomplish main goals first.

So here is my perfect Emacs:
- Beautiful colorscheme
- Vim bases editing
- Spacemacs inspired command invocation (press space then a few mnemonic keys)

If you are familiar with the Emacs landscape you are probably wondering why I dont' just use Spacemacs.
Well, I like Spacemacs a lot but it is bulky and slow on my machine and I feel that I don't need most of what is built in.
Maybe as I become more competent with Emacs I will end up re-implementing most of what Spacemacs does but I see that as a good thing.
By building my perfect system from the ground up I will understand completely how it works and have full control over it.
It might take me 10x as long to get it up and running but over the next 80 years that I plan to use Emacs that control will far outweigh the work it takes to set it up.

* How I'm going to learn Emacs

As much as I want to dive straight into Evil mode and use Vim keybindings, I'm starting with a blank configuration and learning vanilla Emacs first.

I will be learning first from a book called "Teach yourself Emacs in 24 hours."

After reading that I will be diving into Emac's built-in documentation functions (which arguably should be the only way to learn it but I'm lazy).

Then I will start building my configuration file (also know as my .emacs file).

I predict the book will take me two weeks to get through, the built-in documentation another week, and the configuration file the rest of my life.

* Reading the book

My goal with this book is to understand how all the high level pieces of Emacs fit together.
The built-in documentation is great for specific information, but I find it long and hard to read.

Starting with this book I hope I can build a good foundation that will help me find where to focus more in the future.

The book is broken into 24 chapters, each supposedly taking about an hour to learn.

Here is how it went.
