* Callousing

There are places on the human body and in the human mind which used to have callouses.
The loss of those callouses was not always intentional, and not always
for the better.

Callousing is the process of gaining back some toughness towards
certain kinds of stress.

The comforts of modern life are great in many ways, but they make us
weaker in subtle ways without us even knowing it.

Those weaknesses are not always categorically bad things, but they
often degrade our control over our lives and environment.

They reduce our agency.

I believe callousing is important on a pursuit of antifragility.

** The Missing Callouses
+ Strong feet that don't need shoes

  I think most shoes are actually bad for your feet because they
  absorb too much shock and lead you to run with bad form which leads
  to injuries down the road.

+ Solitude and Boredom

  Our minds need space to process life. I believe constant stimulation
  leads to anxiety. Knowing how to be bored is hard, but worth pursing.

+ Cold exposure

  A long, long time ago, if it rained, you got wet. If it snowed, you
  got cold. Exposure to cold is great for our bodies when done smartly
  and great for mental health when experienced voluntarily.

+ Natural dirtiness

  Gut health suffers when we sit in sterile environments all the
  time. We would all benefit from digging around in a garden every
  once in a while.

+ Death

  I've never seen a dead person. American culture has few tools for
  dealing with death in healthy ways. I'm completely seperated from the
  process by which meat arrives in my fridge ready to eat. I'm
  obsessed with living forever.

  Connection to the natural cycles of life and death are probably
  important to staying grounded and living meaningfully.

+ Difficult things in general

  Almost nothing I've done in the last year could be considered
  hard. I believe doing hard things makes you better at doing all
  other hard things. I should work on this.

** The Noble Savage Fallacy

I want to be clear that I'm not saying pre-modern life was better. I
wouldn't trade lives with a caveman who didn't have access to air
conditioning or health care.

I'm just saying that we live much different lives than our ancestors
and occassionally re-evaluating those differences is valuable.
