#+begin_export markdown
export const metadata = {
  title: "Leading Oneself"
}
#+end_export

* Leading Yourself

Most leadership advice boils down to these four things:

- Have a clear mission. Commincate it well.
- Have clear boundaries and expectations. Communicate them well.
- Care deeply about people. Commincate that to them.
- Take genuine ownership over every problem you see.

Most relationship advice is also contatined in those few lines.

And I truly believe that when applied to yourself, it's amazing advice
for personal development.

Leadership, relationships, and personal development are all
fundamentally the same thing: understanding human nature. The only
difference is that with personal development you are not communicating
with a team or a partner, but with yourself.

** Having a mission

Give yourself a clear, grand mission in life.  Only after surrendering
to something bigger than yourself can you reach your full potential.
This mission can change over time, but it should never be
absent. Embed that mission into everything you do.

** Setting Boundaries

Give yourself clear boundaries about what you will never do.  Set
expectations for your standards in life.  The reasoning behind your
boundaries and expectations doesn't even have to be completely
rational as long as it helps you accomplish your mission.

** Self Care

Care deeply about yourself as a beautiful yet flawed human.
Treat yourself how you'd like a boss to treat you.
Validate your goals as worthy uses of your own time.

If you don't support yourself, who will?

** Ownership

If you see a problem in your life, that's *your* problem.  Nobody
will fix it but you.  Tell yourself that and believe it.

** Actionable Leadership

So how do you lead yourself? How can you communicate with yourself? I
believe one answer is journalling.

Journalling forces you to communicate with yourself about your
problems, self-worth, boundaries, and mission.

It gives your mind space to lead.
